# Generated by Django 5.1.2 on 2024-11-01 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faraz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(default=False, max_length=254)),
                ('register', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
