# Generated by Django 5.1.2 on 2024-11-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faraz',
            name='age',
            field=models.IntegerField(default=True),
        ),
    ]
