# Generated by Django 5.1.2 on 2024-11-03 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_faraz_image_name_alter_faraz_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cheif', models.CharField(default='faraz', max_length=100)),
                ('member', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Emplyee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('number', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('slug', models.SlugField(max_length=100)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.company')),
                ('emplyee', models.ManyToManyField(related_name='employee_companies', to='mainapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product_company',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('production_date', models.DateField(max_length=100, null=True)),
                ('produst_price', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('sales', 'Sales'), ('normal', 'Normal')], max_length=100)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_companies', to='mainapp.company')),
            ],
        ),
    ]
